### PR TITLE
1.8 support

### PR DESCRIPTION
**Pull request by Gerrygames**
Support 1.8 clients on 1.9+ servers.

image
image

### CODE REVIEW

**Comment by Matsv** [comment]
I’m sadly not sure (yet) if I want to support 1.8. Like every version that gets pushed, bugs will be found. I currently don’t have the time to handle and fix them. 

I’m hoping that I’ll have more time in the future or find someone that is able to provide support and handle the bugs.

I know it’s such a time consuming job to create 1.8 support and feel an asshole by not directly pulling it, but it’s not maintainable at the moment.

**Comment by Gerrygames** [comment]
Okay. I totally understand you.
I guess I will put this in an extra plugin then. I will close this PR when I am done with it. Any suggestions on the naming of the plugin? :D

**Comment by Matsv** [comment]
ViaLegacy or something like that? (:

**Comment by Gerrygames** [comment]
Yeah I was thinking about that. Myles proposed ViaRewind and I liked that one more :) I did release the plugin now!

**Pull request closed without merging**
